# Generated by Django 4.0.2 on 2022-02-20 20:12

import app.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, upload_to=app.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default='Document', max_length=256),
        ),
        migrations.AddField(
            model_name='document',
            name='upload_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
