# Generated by Django 4.0.2 on 2022-02-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_documentcontainer_document_container'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='container',
        ),
        migrations.AddField(
            model_name='document',
            name='container',
            field=models.ManyToManyField(blank=True, null=True, to='app.DocumentContainer'),
        ),
    ]
