# Generated by Django 4.0.2 on 2022-04-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_document_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='grade',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
