# Generated by Django 4.0.2 on 2022-02-20 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_document_container_document_container'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='container',
            new_name='containers',
        ),
    ]
