# Generated by Django 4.0.2 on 2022-04-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_document_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='s3_private_image_url',
            field=models.URLField(default='', max_length=500),
        ),
    ]
